### ISSUE TITLE
Issue with getCohortCovariateData function

### ISSUE THREAD

**Issue by ChungsooKim** [ohdsi-studies/BipolarMisclassificationValidation#1]
Hi, I'm Chungsoo Kim from South Korea.

I think it's really nice study concept, so I tried to run the validation package in our EHR DB.
But when I ran your validation package, there was a problem related to getCohortCovariateData function like below. 

![image](https://user-images.githubusercontent.com/42205861/72612097-23067400-396f-11ea-9d3e-6ba13577e12b.png)

After the execution of this function separately, other processes had no problems. 
It seems that the function didn't be packed inside the package.

Results of my trial were like below

![image](https://user-images.githubusercontent.com/42205861/72612385-edae5600-396f-11ea-9bf2-ca3549655db2.png)

Thanks
Chungsoo Kim

**Comment by jreps** [comment]
Wow, thanks for quickly testing this Chungsoo Kim :). I added getCohortCovariateData to the NAMESPACE - so hopefully that will solve the issue.
